// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYGHtdhXQpESQeYSEqktqw9RFAGFhQQqY',
    appId: '1:337192108140:web:631fb40104193f384d9849',
    messagingSenderId: '337192108140',
    projectId: 'social-app-60f13',
    authDomain: 'social-app-60f13.firebaseapp.com',
    storageBucket: 'social-app-60f13.firebasestorage.app',
    measurementId: 'G-S03EGR6LHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTleQtLGv1mIGQRqPo3OHENKzAMog_6aU',
    appId: '1:337192108140:android:f470dafbc7de7e174d9849',
    messagingSenderId: '337192108140',
    projectId: 'social-app-60f13',
    storageBucket: 'social-app-60f13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrJAtDw3aaPvEBOmbEkbzRGi4CHfSjPco',
    appId: '1:337192108140:ios:63d7e213b8d058f24d9849',
    messagingSenderId: '337192108140',
    projectId: 'social-app-60f13',
    storageBucket: 'social-app-60f13.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrJAtDw3aaPvEBOmbEkbzRGi4CHfSjPco',
    appId: '1:337192108140:ios:63d7e213b8d058f24d9849',
    messagingSenderId: '337192108140',
    projectId: 'social-app-60f13',
    storageBucket: 'social-app-60f13.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYGHtdhXQpESQeYSEqktqw9RFAGFhQQqY',
    appId: '1:337192108140:web:5df42fe828ee02564d9849',
    messagingSenderId: '337192108140',
    projectId: 'social-app-60f13',
    authDomain: 'social-app-60f13.firebaseapp.com',
    storageBucket: 'social-app-60f13.firebasestorage.app',
    measurementId: 'G-H6LQ48BFW8',
  );
}
